on:
  pull_request:
  branches:
    - main
    - master
  push:
    branches:
    - main
    - master
    - develop
  name: "Build & Release"
jobs:
build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk --debug --split-per-abi
      - run: Push to Release
      - uses: actions/upload-artifact@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number}}
          token: ${{ secrets.TOKEN }}